plugins:
  - jekyll-paginate-v2

defaults:
  - scope:
      path: ""
    values:
      lang: "en"

collections:
  labels:
    output: true
    permalink: /labels/:title

vendors:
  - title: Most popular labels
  - title: Avery
  - title: SheetLabels.com
  - title: OnlineLabels.com
  - title: Herma